export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const ADD_USER_BEGIN = 'ADD_USER_BEGIN'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const GET_ALL_USERS_BEGIN = 'GET_ALL_USERS_BEGIN'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const GET_ALL_TASKS_BEGIN = 'GET_ALL_TASKS_BEGIN'
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCES'

export const ADD_TASK_BEGIN = 'ADD_TASK_BEGIN'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR'

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'

export const EDIT_TASK_BEGIN = 'EDIT_TASK_BEGIN'

export const GET_TASK_BEGIN = 'GET_TASK_BEGIN'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_ERROR = 'GET_TASK_ERROR'

export const ADD_COMMENT_BEGIN = 'ADD_COMMENT'
export const DELETE_COMMENT_BEGIN = 'DELETE_COMMENT'
export const UPDATE_COMMENT_BEGIN = 'UPDATE_COMMENT'

export const ADD_RECORD_BEGIN = 'ADD_RECORD_BEGIN'
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS'
export const ADD_RECORD_ERROR = 'ADD_RECORD_ERROR'

export const GET_ALL_RECORDS_BEGIN = 'GET_ALL_RECORDS_BEGIN'
export const GET_ALL_RECORDS_SUCCESS = 'GET_ALL_RECORDS_SUCCES'

export const DELETE_RECORD_BEGIN = 'DELETE_RECORD_BEGIN'

export const GET_ALL_CLIENTS_BEGIN = 'GET_ALL_CLIENTS_BEGIN'
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS'

export const ADD_CLIENT_BEGIN = 'ADD_CLIENT_BEGIN'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR'

export const GET_ALL_EMPLOYE_SUCCESS = 'GET_ALL_EMPLOYE_SUCCESS'
export const GET_ALL_EMPLOYE_BEGIN = 'GET_ALL_EMPLOYE_BEGIN'

export const ADD_PROJECT_BEGIN = 'ADD_PROJECT_BEGIN'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR'

export const EDIT_PROJECT_BEGIN = 'EDIT_PRPJECT_BEGIN'

export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN'

export const GET_ALL_PROJECT_BEGIN = 'GET_ALL_PROJECT_BEGIN'
export const GET_ALL_PROJECT_SUCCESS = 'GET_ALL_PROJECT_SUCCESS '

export const DELETE_CLIENT_BEGIN = 'DELETE_CLIENT_BEGIN'

export const EDIT_CLIENT_BEGIN = 'EDIT_CLIENT_BEGIN'

export const GET_CLIENT_BEGIN = 'GET_CLIENT_BEGIN'
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const GET_USER_RECORDING_BEGIN = 'GET_USER_RECORDING_BEGIN'
export const GET_USER_RECORDING_SUCCESS = 'GET_USER_RECORDING_SUCCESS'

export const GET_REQUESTS_BEGIN = 'GET_REQUESTS_BEGIN'
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS'

export const UPDATE_REQUEST_BEGIN = 'UPDATE_REQUEST_BEGIN'

export const ADD_APPOINTMENT_BEGIN = 'ADD_APPOINTMENT_BEGIN'
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS'
export const ADD_APPOINTMENT_ERROR = 'ADD_APPOINTMENT_ERROR'

export const GET_APPOINTMENT_BEGIN = 'GET_APPOINTMENT_BEGIN'
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS'
export const GET_APPOINTMENT_ERROR = 'GET_APPOINTMENT_ERROR'
